package com.freddy.plugin.ai;

import java.util.ArrayList;
import java.util.List;

/**
 * FreddyWorkflow - Complete workflow plan
 * 
 * Represents a multi-step plan generated by the LLM planner.
 * Designed to be JSON-serializable.
 */
public class FreddyWorkflow {

    /**
     * Human-readable goal description
     * Example: "CRAFT_IRON_PICKAXE"
     */
    public String goal;

    /**
     * List of steps to execute sequentially
     */
    public List<FreddyStep> steps;

    /**
     * Metadata: creation timestamp
     */
    public long createdAt;

    /**
     * Default constructor for JSON deserialization
     */
    public FreddyWorkflow() {
        this.steps = new ArrayList<>();
        this.createdAt = System.currentTimeMillis();
    }

    /**
     * Constructor with goal
     */
    public FreddyWorkflow(String goal) {
        this.goal = goal;
        this.steps = new ArrayList<>();
        this.createdAt = System.currentTimeMillis();
    }

    /**
     * Add a step to the workflow
     */
    public void addStep(FreddyStep step) {
        steps.add(step);
    }

    /**
     * Validate workflow
     */
    public boolean isValid() {
        if (goal == null || goal.isEmpty()) {
            return false;
        }

        if (steps == null || steps.isEmpty()) {
            return false;
        }

        // Validate each step
        for (FreddyStep step : steps) {
            if (!step.isValid()) {
                return false;
            }
        }

        return true;
    }

    /**
     * Get step count
     */
    public int getStepCount() {
        return steps != null ? steps.size() : 0;
    }

    /**
     * Check if workflow exceeds step limit
     */
    public boolean exceedsStepLimit(int maxSteps) {
        return getStepCount() > maxSteps;
    }

    @Override
    public String toString() {
        return String.format("Workflow[goal=%s, steps=%d]", goal, getStepCount());
    }

    /**
     * Get workflow hash for loop detection
     */
    public String getHash() {
        StringBuilder sb = new StringBuilder();
        sb.append(goal).append("|");
        for (FreddyStep step : steps) {
            sb.append(step.command).append(":").append(step.target).append(":").append(step.quantity).append("|");
        }
        return sb.toString();
    }
}
