package com.freddy.plugin.ai.crafting;

import org.bukkit.Material;

import java.util.Map;

/**
 * GatheringPrompt - LLM prompt builder for gathering operations
 * 
 * CRITICAL CONSTRAINT: This prompt ONLY allows gathering commands.
 * NO crafting commands should be generated by the LLM.
 * 
 * The LLM's job:
 * - Decide HOW to gather primitives (mine vs kill)
 * - Decide WHAT to target (DIAMOND_ORE vs DEEPSLATE_DIAMOND_ORE)
 * - Decide ORDER of operations
 * 
 * The LLM does NOT:
 * - Decide recipes (that's RecipeRegistry)
 * - Invent items (only primitives from the missing list)
 * - Output crafting steps (that's AutoCrafter)
 */
public class GatheringPrompt {

    /**
     * Build gathering prompt for LLM
     * 
     * CRITICAL: Prompt must NEVER suggest material equivalence or alternatives.
     * LLM must ONLY gather exact materials listed.
     */
    public static String build(Material goal, Map<Material, Integer> missing) {

        StringBuilder prompt = new StringBuilder();

        prompt.append("You are a Minecraft gathering planner.\n\n");

        prompt.append("CRITICAL RULES:\n");
        prompt.append("- Output JSON ONLY\n");
        prompt.append("- You may ONLY use these commands:\n");
        prompt.append("    FREDDY_MINE <BLOCK> <QTY>\n");
        prompt.append("    FREDDY_KILL <MOB> <QTY>\n");
        prompt.append("- DO NOT output FREDDY_CRAFT commands\n");
        prompt.append("- DO NOT assume items magically exist\n");
        prompt.append("- DO NOT invent new items\n");
        prompt.append("- YOU MUST gather ONLY the exact blocks listed below\n");
        prompt.append("- DO NOT substitute materials\n");
        prompt.append("- DO NOT choose alternative ores\n");
        prompt.append("- If IRON_ORE is listed, mine ONLY IRON_ORE (not gold, not diamond)\n");
        prompt.append("- Output steps in logical order\n");
        prompt.append("- Maximum 10 steps\n\n");

        prompt.append("Goal: Gather materials for ").append(goal.name()).append("\n\n");

        prompt.append("Missing primitive items:\n");
        for (Map.Entry<Material, Integer> entry : missing.entrySet()) {
            prompt.append("- ").append(entry.getKey().name()).append(" x").append(entry.getValue()).append("\n");
        }
        prompt.append("\n");

        prompt.append("STRICT REQUIREMENT:\n");
        prompt.append("You must gather EXACTLY the materials listed above.\n");
        prompt.append("Do NOT gather any other materials.\n\n");

        prompt.append("Output JSON schema:\n");
        prompt.append("{\n");
        prompt.append("  \"goal\": \"GATHER\",\n");
        prompt.append("  \"steps\": [\n");
        prompt.append(
                "    {\"command\": \"FREDDY_MINE\", \"target\": \"<EXACT_BLOCK_FROM_LIST>\", \"quantity\": <NUMBER>}\n");
        prompt.append("  ]\n");
        prompt.append("}\n\n");

        prompt.append("Output ONLY the JSON, no explanation.\n");

        return prompt.toString();
    }

    /**
     * Build simplified prompt for mock/testing
     */
    public static String buildSimple(Map<Material, Integer> missing) {
        StringBuilder sb = new StringBuilder();
        sb.append("Gather these items:\n");
        for (Map.Entry<Material, Integer> entry : missing.entrySet()) {
            sb.append("- ").append(entry.getKey().name())
                    .append(" x").append(entry.getValue()).append("\n");
        }
        return sb.toString();
    }
}
